### ISSUE TITLE
機能一覧作成

### ISSUE THREAD

**Issue by itasakashogo** [itasakashogo/gomamis#1]

**Comment by Myplanair** [comment]
# test

**Comment by tenchan18** [comment]
```
test
```

**Comment by Myplanair** [comment]
# 設計 (24時間)
## 機能一覧（2時間）（output: メモ書き？）
要件からそれぞれが必要な機能を洗い出し、可視化していく
- ユーザー
  - 購入
- 管理者

**Comment by itasakashogo** [comment]
<img width="200" alt="qiita-square" src="https://qiita-image-store.s3.amazonaws.com/0/126861/90386757-fd96-8ba6-3477-485669713c55.png">

**Comment by Myplanair** [comment]
# 設計 (24時間)
## 機能一覧（2時間）（output: メモ書き？）
要件からそれぞれが必要な機能を洗い出し、可視化していく
- ユーザー
  - 商品処理
     -　検索
  - 会員処理
    - 会員登録
    - 退会
    - ログイン
    - ログアウト
    - プロフィール編集
      - 名前（姓、名）
      - 名前（カナ）
      - 郵便番号
      - 住所
      - 電話番号
      - メールアドレス
      - パスワード

**Comment by kei-sait0** [comment]
# 設計 (24時間)
## 機能一覧（2時間）（output: メモ書き）
要件からそれぞれが必要な機能を洗い出し、可視化していく
### ユーザー機能
#### 商品
- カートの処理
  - 購入
  - 商品の追加
  - 商品の削除
- 商品一覧表示
- 商品詳細表示
- 商品名で検索
- 在庫照会(0だと買えない)
#### 会員
- 会員登録
- 退会
- ログイン(メールアドレス、パスワード)
- ログアウト
- プロフィール編集
  - 名前（姓、名）
  - 名前（カナ）
  - 郵便番号
  - 住所
  - 電話番号
  - メールアドレス
  - パスワード
- 購入履歴
### 管理者
#### 商品
- 新規追加
  - アーティスト名
  - シングル/アルバム名
  - ジャケット画像
  - 値段
  - レーベル名
  - ジャンル
  - シングル/アルバム内の曲名
  - 在庫数
- 削除
- 編集
#### 管理
- ログイン(メールアドレス、パスワード)
- ユーザー一覧表示
- ユーザーの個別表示
- ユーザーの編集
  -  名前（姓、名）
  -  名前（カナ）
  -  郵便番号
  -  住所
  -  電話番号
  -  メールアドレス
  -  パスワード（まじか）
- ユーザーの削除
- ユーザーの購入履歴表示
  - 購入者
  - 購入日
  - 購入内容（シングル/アルバム名、購入枚数、小計など）
  - 購入価格総計
  - 送付先
  - ステータス（受付、商品準備中、出荷済など）
- ステータス更新処理

**Comment by itasakashogo** [comment]
[

データベース名 |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | --
cd_ shop |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |  
テーブル名 |   |   |   |   |   |   |   |  
buy_history | 購入履歴 |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |  
カラム名 | カラムの説明 | PK | データ型 | NOT NULL | auto increment | index | defalt | 備考
user_id | 購入者のID | ○ | integer | ◯ | 有り | 有り |   |  
buy_day | 購入日 |   | integer | ◯ |   |   |   |  
items | 商品 |   | text | ◯ |   |   |   |  
price | 購入価格 |   | string | ◯ |   |   |   |  
address | 配送先 |   | text | ◯ |   |   |   |  

](url)

**Comment by itasakashogo** [comment]
データベース名 |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | --
cd_ shop |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |  
テーブル名 |   |   |   |   |   |   |   |  
buy_history | 購入履歴 |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |  
カラム名 | カラムの説明 | PK | データ型 | NOT NULL | auto increment | index | defalt | 備考
user_id | 購入者のID | ○ | integer | ◯ | 有り | 有り |   |  
buy_day | 購入日 |   | integer | ◯ |   |   |   |  
items | 商品 |   | text | ◯ |   |   |   |  
price | 購入価格 |   | string | ◯ |   |   |   |  
address | 配送先 |   | text | ◯ |   |   |   |

**Comment by itasakashogo** [comment]
<img width="571" alt="2018-05-02 16 50 30" src="https://user-images.githubusercontent.com/37974157/39511685-473ea65e-4e29-11e8-8791-2061a68dfe8a.png">
