### ISSUE TITLE
画面設計

### ISSUE THREAD

**Issue by kei-sait0** [itasakashogo/gomamis#2]

**Comment by kei-sait0** [comment]
手書き終了

**Comment by kei-sait0** [comment]
手書きのみ終わらして、
5/7 に再開する。

**Comment by kei-sait0** [comment]
## Userの画面ページ一覧
![user_all](https://user-images.githubusercontent.com/9780594/39690513-5a347d98-5215-11e8-8f3b-d636af048326.PNG)

**Comment by kei-sait0** [comment]
![admin_all](https://user-images.githubusercontent.com/9780594/39691321-397d2408-5218-11e8-9fc5-2eb509ff2768.PNG)

**Comment by itasakashogo** [comment]
メンター課題
・購入前の画面が足りない
・カートの部分に数量の選択がない
・物理削除と論理削除について調べる
→アカウントが消えた時のIDが関連なくなってしまうから

**Comment by ghost** [comment]
購入画面の前を４つ追加しました。
カートの部分に数量選択を追加。
