### ISSUE TITLE
データベース設計

### ISSUE THREAD

**Issue by kei-sait0** [itasakashogo/gomamis#3]

**Comment by ghost** [comment]
<img width="571" alt="2018-05-02 16 50 30" src="https://user-images.githubusercontent.com/36909021/39692786-d1b93c8a-521c-11e8-99a4-9295383e7516.png">

**Comment by kei-sait0** [comment]
![image](https://user-images.githubusercontent.com/9780594/39696586-1e2a0e4e-5229-11e8-9008-9526608ed745.png)
# 案
## 気にあるところ
- どちらかがnull のカラムであるテーブルを作成してもよいのか。。
- 自己参照っていいの？(Albamにはいるものは、曲、もしくはアルバム）
- Cart は常に1つであるべき？order は確定のものを保存。
Cartが常にひとつならばクラスを作成すればよくない？（セッションで管理？）

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/36909021/39755287-36927f16-5300-11e8-959b-9be29436cd11.png)

# 気になる所
delete_flagの使い方が分からない(delete_flagを有効にした時に、そのユーザーが再度会員登録した時に、もう一度できるようにするにはどうづればいいのか？)
## 検索
もし、検索機能を付けた場合アーティストテーブルを付けないと、アーティスト名で検索をかけれない。
CDの新規登録をする際に、入力の仕方を登録しておかないと、スペースが入っているいない、平仮名やローマ字で検索をかけた時に検索できないのでは、ないか？

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/36909021/39853174-93812248-545b-11e8-9d1c-a7cfe4a7c372.png)

- 暫定的に決定（songは今の所置いておく）

**Comment by itasakashogo** [comment]
![image](https://user-images.githubusercontent.com/37974157/39869460-8b1d373a-5498-11e8-9954-b3c1c0c99129.png)

一旦、あげておきます

**Comment by kei-sait0** [comment]
ありがとうございます～
