### ISSUE TITLE
アプリケーション設計

### ISSUE THREAD

**Issue by kei-sait0** [itasakashogo/gomamis#4]

**Comment by ghost** [comment]
簡単にURL設定をしました、ですがやんわりとしかきめてないので再度検討する必要があります。

**Comment by ghost** [comment]
今回使用するであろう、gem達。
- devise
- refile
- kaminari
- (ransack)

**Comment by ghost** [comment]
カートに追加した時に、他者に購入されてしまったら、カートを追加している人に、購入できなくするにはどうすればいいのか？

**Comment by kei-sait0** [comment]
カート追加後に、他の人が購入したため、商品在庫が0、もしくは購入した数に満たない状況となる。
この状況で購入させない仕組みを作成したいということですかね。
購入確定ボタンを押したときに、商品の在庫数をデータベースからひっぱてきて
購入数に満たない場合のエラー処理をすれば良いと思います。
```
if (購入数 > 在庫数) 
 購入できなかった時の処理を記載
 （Cart ページに飛ばしてあげ、"在庫がありません"とメッセージを表示させる）
else
 購入できた時の処理
```
あくまで例です～
